languageCode = 'en-GB'
title = 'Ursula Jakob'

# Disable categories and tags
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  description = "The work of the Bern-based artist Ursula Jakob"

[imaging]
  quality = 75
  resampleFilter = "Lanczos"
[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[module]
# replacements = 'github.com/glasgowartist/ga-hugo -> ../../ga'

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/glasgowartist/ga-hugo'

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "main\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
